project:
  type: website

execute:
  freeze: auto

website:
  title: "Enrico Wegner"
  site-url: https://enweg.github.io
  description: This is the private website of Enrico Wegner.
  page-footer: "Copyright 2025, Enrico Wegner"
  search: false
  navbar:
    title: false
    left:
      - text: Enrico Wegner
        href: index.qmd
    right:
      - text: Research
        href: research.qmd
      - text: Software
        href: software.qmd
      - text: Blog
        href: blog.qmd
      - text: More
        menu:
          - text: CV
            icon: person
            href: assets/CV_Enrico_Wegner.pdf
          - text: GitHub
            icon: github
            href: https://github.com/enweg
          - text: LinkedIn
            icon: linkedin
            href: https://www.linkedin.com/in/enrico-wegner-2bb8a717b/
  cookie-consent: false
format:
  html:
    theme: flatly
    css: styles.css
