---
title: Research
title-block-banner: true
description: "This page provides an overview of my research conducted during my PhD and my time at the OECD. Some of these papers also build on work from my master’s thesis, which focused on Bayesian Neural Networks."
---

## Working Papers

### [Transmission Channel Analysis in Dynamic Models](https://arxiv.org/abs/2405.18987)

**2025 (first edition 2024)**

We propose a framework for analysing transmission channels in a large class of dynamic models. We formulate our approach both using graph theory and potential outcomes, which we show to be equivalent. Our method, labelled Transmission Channel Analysis (TCA), allows for the decomposition of total effects captured by impulse response functions into the effects flowing through transmission channels, thereby providing a quantitative assessment of the strength of various well-defined channels. We establish that this requires no additional identification assumptions beyond the identification of the structural shock whose effects the researcher wants to decompose. Additionally, we prove that impulse response functions are sufficient statistics for the computation of transmission effects. We demonstrate the empirical relevance of TCA for policy evaluation by decomposing the effects of policy shocks arising from a variety of popular macroeconomic models.

- Paper: [arxiv](https://arxiv.org/abs/2405.18987)
- Replication codes: [GitHub](https://github.com/enweg/tca-replication-material)
- Related code: [TransmissionChannelAnalysis.jl](https://enweg.github.io/tca-website)

## Publications

### [Quantifying Uncertainty of Portfolios using Bayesian Neural Networks](https://doi.org/10.1109/IJCNN60899.2024.10650382)

International Joint Conference on Neural Networks (IJCNN)<br>**2024**

Quantifying the uncertainty of a financial portfolio is important for investors and regulatory agencies. Reporting such uncertainty accurately is challenging due to time-dependent market dynamics, non-linearities in the return and risk properties of a portfolio, and due to the unobserved nature of the market risk. We propose Bayesian Neural Network (BNN) models, namely Recurrent Neural Network (RNN) and Long Short Term Memory (LSTM) models, to estimate the time-varying return distribution of an asset portfolio. The proposed models estimate the density of returns and incorporate parameter uncertainty through Bayesian inference. The uncertainty and any financial risk metric of interest can directly be obtained from the estimated density. Furthermore, through the BNN input-output design, proposed BNNs incorporate potential non-linear effects of each asset in the portfolio on the obtained density estimates. The proposed method is applicable to assess the uncertainty of any portfolio where the portfolio weight optimization is separated from risk assessment. We analyze the risk of a daily, equally weighted portfolio of 29 ETFs and a risk-free asset for a long time span with differing market environments between 09/06/2005 and 10/09/2020. We study the effects of different inference methods on the obtained results. The proposed models improve portfolio risk estimates compared to the benchmark. The performances of the proposed models depend on BNN design and the inference method. RNN models lead to relatively more stable results compared to LSTMs. Furthermore, the results of models with a relatively higher number of parameters depend heavily on the estimation method.

- Paper: [https://doi.org/10.1109/IJCNN60899.2024.10650382](https://doi.org/10.1109/IJCNN60899.2024.10650382)

## OECD Working Papers

### [Recent Trends in Transport and Insurance Costs and Estimates at Disaggregated Product Level](https://doi.org/10.1787/b5dbab02-en)

**2022**

This paper updates the OECD International Transport and Insurance Cost (ITIC) of Merchandise Trade database, which covers more than 180 countries and partners, and over 1000 products from 1995 to 2020. Transport and insurance costs, also known as CIF-FOB margins, are estimated using a gravity model. A cross-validation procedure is used to evaluate model performance. In addition to describing the methodology, the paper highlights that transport and insurance costs are declining as a fraction of trade value, but this reduction has been flattening out in more recent years. However, an alternative measure, the explicit CIF-FOB margins per kilogramme imported, suggests that transport and insurance costs have been actually rising since 2002. Both CIF-FOB margins and cost per kilogramme imported show increases in 2020 when compared to 2019. This is robust to corrections for compositional changes. The methodology is used to produce the International Transport and Insurance Costs of Merchandise Trade data base and the data is made publically available on .Stat under the International Trade and Balance of Payments heading.

- Paper: [OECD iLibrary](https://doi.org/10.1787/b5dbab02-en)

### [Using Unit Value Indices as Proxies for International Merchandise Trade Prices](https://doi.org/10.1787/27a5abd7-en)

**2022**

In light of the need for detailed and timely internationally comparable trade price indices, this paper describes a multi-tiered methodology to mitigate many of the empirical challenges associated with using customs data, to provide more robust estimates of unit value indices (UVIs) by country and product. UVIs are available for both exports and imports, by reporting country and the CPA 2-digit level of classification. Although the approach cannot capture changes in the quality of products nor compositional changes happening at a lower than HS 6-digit classification, the results indicate that at higher levels of aggregation (SITC 1-digit level), estimated UVIs closely follow price changes obtained from other sources. This is observed both for products with significant and rapid quality changes, such as hi-tech products, and for products with a low rate of quality changes, such as commodities, other primary and low-tech goods. Furthermore, products where little quality change occurs over time show similarity between UVIs and price changes from other sources at lower levels of disaggregation. The methodology is used to produce the Merchandise Trade Price Index and the data is made publically available on .Stat under the International Trade and Balance of Payments heading.

- Paper: [OECD iLibrary](https://doi.org/10.1787/27a5abd7-en)
